export const GET_PRODUCTS = 'PRODUCTS/GET_PRODUCTS';
export const INC_PAGE = 'PRODUCTS/INC_PAGE';

export const SHOW_LOADER = 'PRODUCTS/SHOW_LOADER';
export const HIDE_LOADER = 'PRODUCTS/HIDE_LOADER';

export const SHOW_ALERT = 'PRODUCTS/SHOW_ALERT';
export const HIDE_ALERT = 'PRODUCTS/HIDE_ALERT';

export const CHANGE_FILTER = 'FILTER/CHANGE_FILTER';